name: CollectiveCulture
favicon: null
layout_spectrum: 0.9250233911443502
typography_spectrum: 0.19463845691643655
title: Collective Culture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.35864785965532064
  lightness: 0.3792352231685072
  saturation: 0.5557939794380218
  rhythmicContrast: 0.9283008268103004
purpose: []
