name: EVOL EMPIRE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06746
title: EVOL EMPIRE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040807'
    - '#9daeb3'
    - '#424d4f'
    - '#5c6f6b'
    - '#d4e0e3'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
