name: CollectiveCulture
favicon: null
layout_spectrum: 0.9027
typography_spectrum: 0.35456
title: EVOL EMPIRE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#393939'
    - '#49bdb1'
    - '#acacac'
    - '#0d0d0d'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
