name: CollectiveCulture
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19463845691643655
title: Collective Culture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#181532'
    - '#563260'
    - '#abaab2'
    - '#ad6895'
  brandStrength: 0.625
  lightness: 0.3792352231685072
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
